=== sol-ide/next/external/win32/xsltproc/docs/en/xsldoc.dtd
<!-- 
     File : xsldoc.dtd     
     Author: Keith Isdale <k_isdale@tpg.com.au>
     Description: Documentation type definition for xsldoc.xml
     Copyright Reserved Under GPL     

Refer to this DTD via 

<!DOCTYPE xsldoc PUBLIC "-//xsldbg//DTD xsldoc XML V1.0//EN" "xsldoc.dtd">

-->

<!ELEMENT xsldoc (overview, cmd+)>
<!ELEMENT overview (header, body, footer)+>
<!ELEMENT header (#PCDATA)>
<!ELEMENT body (title?, para)+>
<!ELEMENT footer (#PCDATA)>
<!ELEMENT para (#PCDATA|text|list|link)* >
<!ATTLIST para 
   title CDATA #IMPLIED
>

<!ELEMENT list (li+)>
<!ELEMENT li (#PCDATA |list| text| comment|link)* >
<!ELEMENT text (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT comment (#PCDATA)>

<!ELEMENT cmd (summary, body? , usage)>
<!ATTLIST cmd 
    name CDATA #REQUIRED
    shortcut CDATA #IMPLIED
    title CDATA #IMPLIED
>

<!ELEMENT usage (li+)>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT command (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link href CDATA #REQUIRED>

=== sol-ide/next/external/win32/xsltproc/docs/en/xsldoc.xml
<?xml version="1.0"?>
<!DOCTYPE xsldoc PUBLIC "-//xsldbg//DTD xsldoc XML V1.0//EN" "xsldoc.dtd">
<!-- 
     File : xsldoc.xml     
     Author: Keith Isdale <k_isdale@tpg.com.au>
     Description: Xml Data to be processed generate help text and other 
                  documentation
     Copyright Reserved Under GPL     
-->
<xsldoc>
<overview>
<header>xsldbg help</header>
<body>
<para> xsldbg is a text based tool to debug stylesheets (the eXtensible Stylesheet Language) and has 
commands similar to the Unix/Linux debugger gdb. It has three major modes of execution of stylesheets.
<list>
<li>Run the whole stylesheet</li>
<li>Step to next xsl instruction</li>
<li>Continue until next break point is found, or stylesheet has restarted</li>
</list>
</para>
<para title="xsldbg command line">
On systems with readline library available you can use the back/forward
keys to navigate the history of entered commands.
On all systems the last entered command can be repeated by just pressing
the &lt;ENTER&gt; key. 
</para>
<para>
If your operating system supports it file names will be expanded. 
</para>
<para>Several commands take more that one argument. Some arguments can be 
 sourrounded by quotes to complex argument to be proceesed as one 
  argument. eg break quot;* | @quot; would allow you to se a breakpoint on the 
  template with the name quot;* | @quot;</para>
<para title="Legend :">
<list><li>TEMPLATE_NAME : A valid template name contains only ASCI character codes 0x00 to 0x7F. And can be a fully qualified name ie "xsl:templateName". </li>
<li>FILENAME : A valid file name local to the system of the user. It can have a &quot;~&quot; prefix on *nix and CYGWIN platforms. Or environment variables under RISC OS</li>
<li>URI : A Uniform Resource Identifiers as defined by RFC 2396</li>
<li>MODE_NAME The mode of template which can be fully qualified name ie "xsl:modeName".</li>
<li>QNAME : A fully qualified name ie "xsl:localPart"</li>
<li>LINENO : A valid line number in associated &lt;FILENAME&gt;</li>
<li>NUMBER_OF_FRAMES : A valid line number frames to change position by</li>
<li>BREAKPOINT_ID : A valid break point number</li>
<li>WATCH_ID : A valid watch expression number as indicated by showwatch command</li>
<li>SPEED: speed to walk through code at, between 0 to 9</li>
<li><comment>(Comment)</comment>: a comment about command meaning or usage</li>
<li>{ opt1 | opt2 | opt2 .. etc} : Choose one of the opt's</li>
<li>XPATH : a xpath selection of node(s)</li>
<li>PARAM_ID : a valid parameter number as indicated by showparam command</li>
<li>PATH : A path to change working directory to On some operating systems a &quot;~&quot; prefix will be replaced by your home directory path</li>
<li>TEXT : Free form text <comment>(no restrictions)</comment></li>
<li>COMMAND : A valid command for the xsdbg</li>
<li>QNAME : A valid variable/parameter name</li>
<li>SOURCE : The stylesheet being/to be executed. See &lt;FILENAME&gt; and &lt;URI&gt;</li>
<li>DATA : The xml data(document) being/to be processed by the stylesheet. See &lt;FILENAME&gt; and &lt;URI&gt;</li>
<li>DEVICE_PATH : Is a valid terminal on the operating system</li>
<li>TTY_LEVEL : Is a valid level of input/output to use</li>

</list>
</para>

<!-- - - - - Start help summary - - - - - -->
<para title="Within xsldbg these commands are available:">
<list>

<li>Help related :<link href="help">help</link></li>

<li>Running related : {<link href="bye">bye</link>|<link href="exit">exit</link>|
<link href="quit">quit</link>}, <link href="step">step</link>, 
<link href="stepup">stepup</link>, <link href="stepdown">stepdown</link>,
<link href="next">next</link>,
<link href="continue">continue</link>, <link href="run">run</link>,
<link href="trace">trace</link>, <link href="setoption">setoption</link>,
<link href="options">options</link> 
</li>

<li>Libxslt parameter related : <link href="addparam">addparam</link>,
<link href="delparam">delparam</link>,<link href="showparam">showparam</link>,
<link href="output">output</link>, <link href="setoption">setoption</link>, 
<link href="options">options</link>  
</li>

<li>Template related : <link href="templates">templates</link>,
<link href="where">where</link>, <link href="frame">frame</link>
</li>

<li>Break point related : <link href="break">break</link>, 
<link href="showbreak">showbreak</link>,<link href="delete">delete</link>, 
<link href="enable">enable</link>
</li>

<li>Expression viewing(xpath) : <link href="cat">cat</link></li>
<li>Node viewing : <link href="ls">ls</link>, <link href="dir">dir</link>, 
<link href="du">du</link>, <link href="cat">cat</link>, <link href="pwd">pwd</link></li>, <link href="addwatch">addwatch</link>, <link href="showwatch">showwatch</link>, <link href="delwatch">delwatch</link>
<li>Variable viewing : <link href="globals">globals</link>, 
<link href="locals">locals</link>, 
<link href="cat">cat</link>
</li>

<li>Variable setting: <link href="set">set</link> </li>

<li>Node selection : <link href="source">source</link>, 
<link href="data">data</link>, <link href="cd">cd</link>
</li>

<li>Searching :<link href="search">search</link>
</li>

<li>Operating system related :<link href="chdir">chdir</link>,
<link href="shell">shell</link>,<link href="tty">tty</link>

</li>

<li>File related : <link href="output">output</link>, 
<link href="entities">entities</link>, <link href="system">system</link>, 
<link href="public">public</link>
</li>

<li>Disabled file commands: <link href="validate">validate</link>, 
<link href="load">load</link>, <link href="save">save</link>, 
<link href="write">write</link>, <link href="free">free</link>
</li>
</list>
</para>
</body>

<footer></footer>
</overview>

<!-- - - - - -  Help related commands - - - - - - - - -  - -->
<cmd name="help" shortcut="h" title="Help">
<summary>Display help on command or overiew</summary>
<body>
<para>Shortcut name: h</para>
</body>
<usage>
<li>help   <comment>(Show overview of product)</comment></li>
<li>help &lt;COMMAND&gt; <comment>(Show help about a command)</comment></li>
</usage>
</cmd>

<!-- - - - - - -  Running related commands - - - - - - - - -->
<cmd name="bye" title="Bye">
<summary>Exit processing stylesheet as soon as possible.</summary>
<usage>
<li>
<text>bye</text>
</li>
</usage>
</cmd>

<cmd name="quit" shortcut="q" title="Quit">
<summary>Exit processing stylesheet as soon as possible.</summary>
<body>
<para>Shortcut name: q</para>
</body>
<usage>
<li>
<text>quit</text>
</li>
</usage>
</cmd>

<cmd name="exit" title="Exit">
<summary>Exit processing stylesheet as soon as possible.</summary>
<usage>
<li>
<text>exit</text>
</li>
</usage>
</cmd>

<cmd name="step" shortcut="s" title="Step">
<summary>Step until next stylesheet instruction.</summary>
<body>
<para>Shortcut name: s</para>
</body>
<usage>
<li>
<text>step</text>
</li>
</usage>
</cmd>

<cmd name="stepup" shortcut="up" title="Stepup">
<summary>Step up to a older "call frame".  </summary>
<body>
<para>Shortcut name: up</para>
<para>This is not an accurate command, xsldbg will stop as close as it can. </para>
</body>
<usage>
<li>
<text>stepup </text>
<comment>(step up one frame)</comment></li>
<li>
<text>stepup &lt;NUMBER_OF_FRAMES&gt; </text>
<comment>(step up specified number of frames)</comment>
</li>
</usage>
</cmd>

<cmd name="stepdown" shortcut="down" title="Stepdown">
<summary>Step down to a newer "call frame".  </summary>
<body>
<para>Shortcut name: down</para>
</body>
<usage>
<li>
<text>stepdown </text>
<comment>(step down one frame)</comment>
</li>
<li>
<text>stepdown &lt;NUMBER_OF_FRAMES&gt;</text>
<comment>(step down specified number of frames)</comment>
</li>
</usage>
</cmd>

<cmd name="next" shortcut="n" title="Next">
<summary>Skip over an xsl:call-template or xsl:apply-templates.
This command has the same effect of entering the commands &quot;step&quot; and then &quot;up&quot;</summary>
<body>
<para>Shortcut name: n</para>
</body>
<usage>
<li>
<text>next</text>
<comment>(proceed to next sibling instruction)</comment>
</li>
</usage>
</cmd>

<cmd name="continue" shortcut="c" title="Continue">
<summary>Continue running stylesheet, stopping at any break points found.</summary>
<body>
<para>Shortcut name: c</para>
</body>
<usage>
<li>
<text>continue</text>
</li>
</usage>
</cmd>

<cmd name="run" shortcut="r" title="Run">
<summary>Restart the stylesheet.</summary>
<body>
<para>Shortcut name: r</para>
</body>
<usage>
<li>
<text>run</text>
</li>
</usage>
</cmd>

<cmd name="trace" title="Trace">
<summary>Trace one execution of the stylesheet</summary>
<usage>
<li>
<text>trace</text>
</li>
</usage>
</cmd>

<cmd name="walk" title="Walk">
<summary>Walk through code using a range of speeds</summary>
<usage>
<li>
<text>walk &lt;SPEED&gt;</text>
<comment>(Use Ctrl-c to stop execution, &lt;SPEED&gt; is a value between 0 and 9. Where 0 means stop, 1 is very fast, 9 is very slow)</comment>
</li>
</usage>
</cmd>

<!-- - - - - - - - libxslt Parameter related - - - - -->
<cmd name="addparam" title="Addparam">
<summary>Add a libxslt parameter</summary>
<usage>
<li>
<text>addparam &lt;QNAME&gt; &lt;XPATH&gt;</text>
<comment>(The &lt;XPATH&gt; must not contain any spaces nor double quotation marks.No error checking done on the validity of &lt;QNAME&gt; nor &lt;XPATH&gt;. This is equivalent to providing --param &lt;QNAME&gt; &lt;XPATH&gt; via command line.)</comment>
</li>
<li>
<text>add param &lt;QNAME&gt; &quot;&lt;XPATH&gt;&quot;</text>  
<comment>(Must not contain double quotation marks in &lt;XPATH&gt;)</comment></li>
</usage>
</cmd>

<cmd name="delparam" title="Delparam">
<summary>Delete a libxslt parameter</summary>
<usage>
<li>
<text>delparam</text>
<comment>(Delete all parameters present)</comment>
</li>
<li>
<text>delparam &lt;PARAM_ID&gt;</text>
</li>
</usage>
</cmd>

<cmd name="showparam" title="Showparam">
<summary>Print the libxslt parameters present</summary>
<usage>
<li>
<text>showparam</text>
</li>
</usage>
</cmd>

<cmd name="setoption" title="Setoption">
